sudo: false
language: ruby
rvm:
  - 2.5.3
before_install:
  - "sudo apt-get install xclip gtk2.0 pkg-config --no-install-recommends --yes"
  - gem install bundler -v 1.17.1
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
